version: "3.7"

services:
  server:
    build:
      context: ./server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules # Required to persist node_modules between container stop/starts.
    ports:
      - 6000:6000
    env_file: ./server/.env

  client:
    build:
      context: ./client
    # This will force server service to build and start before client.
    depends_on:
      - server
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules # Required to persist node_modules between container stop/starts.
    ports:
      - 3001:3001
    environment:
      CHOKIDAR_USEPOLLING: "true"
